### ISSUE TITLE
Not applying before packaging

### ISSUE THREAD

**Issue by jadar** [stringcode86/pureawesome#1]
If I change the build number and then immediately do an archive, the script runs but the old icon is still applied to the app.

<img width="683" alt="screen_shot_2015-11-24_at_11_10_26_am" src="https://cloud.githubusercontent.com/assets/3793928/11374708/0cc904c8-929d-11e5-97f6-a91eddc3b541.png">

**Comment by stringcode86** [comment]
If this happens for iPhone target make sure you drag "Make Beta Icon" right below target dependencies. (I think there is a bug in Xcode which makes this dragging maddening).

Likely you mean watch app target. Quick fix would be copy and paste script from iPhone build phase into watch app extension build phase.
